package net.sf.jremoterun.utilities.nonjdk.javalangutils

import groovy.transform.CompileStatic

/**
 * Options that starts with -XX
 * https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html
 * https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html
 * // Run to get file content : -XX:+PrintFlagsFinal
 * @see net.sf.jremoterun.utilities.nonjdk.lang.JavaDiagnostic2Options#VM_flags(true)
 */
@CompileStatic
class JavaCmdOptionsNotStd2 {

    public Integer ActiveProcessorCount; // = -1                                  {product}
    public Integer AdaptiveSizeDecrementScaleFactor; // = 4                                   {product}
    public Integer AdaptiveSizeMajorGCDecayTimeScale; // = 10                                  {product}
    public Integer AdaptiveSizePausePolicy; // = 0                                   {product}
    public Integer AdaptiveSizePolicyCollectionCostMargin; // = 50                                  {product}
    public Integer AdaptiveSizePolicyInitializingSteps; // = 20                                  {product}
    public Integer AdaptiveSizePolicyOutputInterval; // = 0                                   {product}
    public Integer AdaptiveSizePolicyWeight; // = 10                                  {product}
    public Integer AdaptiveSizeThroughPutPolicy; // = 0                                   {product}
    public Integer AdaptiveTimeWeight; // = 25                                  {product}
    public Boolean AdjustConcurrency; // = false                               {product}
    public Boolean AggressiveHeap; // = false                               {product}
    public Boolean AggressiveOpts; // = false                               {product}
    public Integer AliasLevel; // = 3                                   {C2 product}
    public Boolean AlignVector; // = false                               {C2 product}
    public Integer AllocateInstancePrefetchLines; // = 1                                   {product}
    public Integer AllocatePrefetchDistance; // = 192                                 {product}
    public Integer AllocatePrefetchInstr; // = 3                                   {product}
    public Integer AllocatePrefetchLines; // = 4                                   {product}
    public Integer AllocatePrefetchStepSize; // = 64                                  {product}
    public Integer AllocatePrefetchStyle; // = 1                                   {product}
    public Boolean AllowJNIEnvProxy; // = false                               {product}
    public Boolean AllowNonVirtualCalls; // = false                               {product}
    public Boolean AllowParallelDefineClass; // = false                               {product}
    public Boolean AllowUserSignalHandlers; // = false                               {product}
    public Boolean AlwaysActAsServerClassMachine; // = false                               {product}
    public Boolean AlwaysCompileLoopMethods; // = false                               {product}
    public Boolean AlwaysLockClassLoader; // = false                               {product}
    public Boolean AlwaysPreTouch; // = false                               {product}
    public Boolean AlwaysRestoreFPU; // = false                               {product}
    public Boolean AlwaysTenure; // = false                               {product}
    public Boolean AssertOnSuspendWaitFailure; // = false                               {product}
    public Boolean AssumeMP; // = false                               {product}
    public Integer AutoBoxCacheMax; // = 128                                 {C2 product}
    public Integer AutoGCSelectPauseMillis; // = 5000                                {product}
    public Integer BCEATraceLevel; // = 0                                   {product}
    public Integer BackEdgeThreshold; // = 100000                              {pd product}
    public Boolean BackgroundCompilation; // = true                                {pd product}
    public Integer BaseFootPrintEstimate; // = 268435456                           {product}
    public Integer BiasedLockingBulkRebiasThreshold; // = 20                                  {product}
    public Integer BiasedLockingBulkRevokeThreshold; // = 40                                  {product}
    public Integer BiasedLockingDecayTime; // = 25000                               {product}
    public Integer BiasedLockingStartupDelay; // = 4000                                {product}
    public Boolean BindGCTaskThreadsToCPUs; // = false                               {product}
    public Boolean BlockLayoutByFrequency; // = true                                {C2 product}
    public Integer BlockLayoutMinDiamondPercentage; // = 20                                  {C2 product}
    public Boolean BlockLayoutRotateLoops; // = true                                {C2 product}
    public Boolean BranchOnRegister; // = false                               {C2 product}
    public Boolean BytecodeVerificationLocal; // = false                               {product}
    public Boolean BytecodeVerificationRemote; // = true                                {product}
    public Boolean C1OptimizeVirtualCallProfiling; // = true                                {C1 product}
    public Boolean C1ProfileBranches; // = true                                {C1 product}
    public Boolean C1ProfileCalls; // = true                                {C1 product}
    public Boolean C1ProfileCheckcasts; // = true                                {C1 product}
    public Boolean C1ProfileInlinedCalls; // = true                                {C1 product}
    public Boolean C1ProfileVirtualCalls; // = true                                {C1 product}
    public Boolean C1UpdateMethodData; // = true                                {C1 product}
    public Integer CICompilerCount; // = 4                                   {product}
    public Boolean CICompilerCountPerCPU; // = true                                {product}
    public Boolean CITime; // = false                               {product}
    public Boolean CMSAbortSemantics; // = false                               {product}
    public Integer CMSAbortablePrecleanMinWorkPerIteration; // = 100                                 {product}
    public Integer CMSAbortablePrecleanWaitMillis; // = 100                                 {manageable}
    public Integer CMSBitMapYieldQuantum; // = 10485760                            {product}
    public Integer CMSBootstrapOccupancy; // = 50                                  {product}
    public Boolean CMSClassUnloadingEnabled; // = true                                {product}
    public Integer CMSClassUnloadingMaxInterval; // = 0                                   {product}
    public Boolean CMSCleanOnEnter; // = true                                {product}
    public Boolean CMSCompactWhenClearAllSoftRefs; // = true                                {product}
    public Integer CMSConcMarkMultiple; // = 32                                  {product}
    public Boolean CMSConcurrentMTEnabled; // = true                                {product}
    public Integer CMSCoordinatorYieldSleepCount; // = 10                                  {product}
    public Boolean CMSDumpAtPromotionFailure; // = false                               {product}
    public Boolean CMSEdenChunksRecordAlways; // = true                                {product}
    public Integer CMSExpAvgFactor; // = 50                                  {product}
    public Boolean CMSExtrapolateSweep; // = false                               {product}
    public Integer CMSFullGCsBeforeCompaction; // = 0                                   {product}
    public Integer CMSIncrementalDutyCycle; // = 10                                  {product}
    public Integer CMSIncrementalDutyCycleMin; // = 0                                   {product}
    public Boolean CMSIncrementalMode; // = false                               {product}
    public Integer CMSIncrementalOffset; // = 0                                   {product}
    public Boolean CMSIncrementalPacing; // = true                                {product}
    public Integer CMSIncrementalSafetyFactor; // = 10                                  {product}
    public Integer CMSIndexedFreeListReplenish; // = 4                                   {product}
    public Integer CMSInitiatingOccupancyFraction; // = -1                                  {product}
    public Integer CMSIsTooFullPercentage; // = 98                                  {product}
    public Double CMSLargeCoalSurplusPercent; // = 0.950000                            {product}
    public Double CMSLargeSplitSurplusPercent; // = 1.000000                            {product}
    public Boolean CMSLoopWarn; // = false                               {product}
    public Integer CMSMaxAbortablePrecleanLoops; // = 0                                   {product}
    public Integer CMSMaxAbortablePrecleanTime; // = 5000                                {product}
    public Integer CMSOldPLABMax; // = 1024                                {product}
    public Integer CMSOldPLABMin; // = 16                                  {product}
    public Integer CMSOldPLABNumRefills; // = 4                                   {product}
    public Integer CMSOldPLABReactivityFactor; // = 2                                   {product}
    public Boolean CMSOldPLABResizeQuicker; // = false                               {product}
    public Integer CMSOldPLABToleranceFactor; // = 4                                   {product}
    public Boolean CMSPLABRecordAlways; // = true                                {product}
    public Integer CMSParPromoteBlocksToClaim; // = 16                                  {product}
    public Boolean CMSParallelInitialMarkEnabled; // = true                                {product}
    public Boolean CMSParallelRemarkEnabled; // = true                                {product}
    public Boolean CMSParallelSurvivorRemarkEnabled; // = true                                {product}
    public Integer CMSPrecleanDenominator; // = 3                                   {product}
    public Integer CMSPrecleanIter; // = 3                                   {product}
    public Integer CMSPrecleanNumerator; // = 2                                   {product}
    public Boolean CMSPrecleanRefLists1; // = true                                {product}
    public Boolean CMSPrecleanRefLists2; // = false                               {product}
    public Boolean CMSPrecleanSurvivors1; // = false                               {product}
    public Boolean CMSPrecleanSurvivors2; // = true                                {product}
    public Integer CMSPrecleanThreshold; // = 1000                                {product}
    public Boolean CMSPrecleaningEnabled; // = true                                {product}
    public Boolean CMSPrintChunksInDump; // = false                               {product}
    public Boolean CMSPrintEdenSurvivorChunks; // = false                               {product}
    public Boolean CMSPrintObjectsInDump; // = false                               {product}
    public Integer CMSRemarkVerifyVariant; // = 1                                   {product}
    public Boolean CMSReplenishIntermediate; // = true                                {product}
    public Integer CMSRescanMultiple; // = 32                                  {product}
    public Integer CMSSamplingGrain; // = 16384                               {product}
    public Boolean CMSScavengeBeforeRemark; // = false                               {product}
    public Integer CMSScheduleRemarkEdenPenetration; // = 50                                  {product}
    public Integer CMSScheduleRemarkEdenSizeThreshold; // = 2097152                             {product}
    public Integer CMSScheduleRemarkSamplingRatio; // = 5                                   {product}
    public Double CMSSmallCoalSurplusPercent; // = 1.050000                            {product}
    public Double CMSSmallSplitSurplusPercent; // = 1.100000                            {product}
    public Boolean CMSSplitIndexedFreeListBlocks; // = true                                {product}
    public Integer CMSTriggerInterval; // = -1                                  {manageable}
    public Integer CMSTriggerRatio; // = 80                                  {product}
    public Integer CMSWaitDuration; // = 2000                                {manageable}
    public Integer CMSWorkQueueDrainThreshold; // = 10                                  {product}
    public Boolean CMSYield; // = true                                {product}
    public Integer CMSYieldSleepCount; // = 0                                   {product}
    public Integer CMSYoungGenPerWorker; // = 67108864                            {pd product}
    public Integer CMS_FLSPadding; // = 1                                   {product}
    public Integer CMS_FLSWeight; // = 75                                  {product}
    public Integer CMS_SweepPadding; // = 1                                   {product}
    public Integer CMS_SweepTimerThresholdMillis; // = 10                                  {product}
    public Integer CMS_SweepWeight; // = 75                                  {product}
    public Boolean CheckEndorsedAndExtDirs; // = false                               {product}
    public Boolean CheckJNICalls; // = false                               {product}
    public Boolean ClassUnloading; // = true                                {product}
    public Boolean ClassUnloadingWithConcurrentMark; // = true                                {product}
    public Integer ClearFPUAtPark; // = 0                                   {product}
    public Boolean ClipInlining; // = true                                {product}
    public Integer CodeCacheExpansionSize; // = 65536                               {pd product}
    public Integer CodeCacheMinimumFreeSpace; // = 512000                              {product}
    public Boolean CollectGen0First; // = false                               {product}
    public Boolean CompactFields; // = true                                {product}
    public Integer CompilationPolicyChoice; // = 3                                   {product}
    public String CompileCommand; // =                                     {product}
    public File CompileCommandFile; // =                                     {product}
    public String CompileOnly; // =                                     {product}
    public Integer CompileThreshold; // = 10000                               {pd product}
    public Boolean CompilerThreadHintNoPreempt; // = true                                {product}
    public Integer CompilerThreadPriority; // = -1                                  {product}
    public Integer CompilerThreadStackSize; // = 0                                   {pd product}
    public Integer CompressedClassSpaceSize; // = 1073741824                          {product}
    public Integer ConcGCThreads; // = 0                                   {product}
    public Integer ConditionalMoveLimit; // = 3                                   {C2 pd product}
    public Integer ContendedPaddingWidth; // = 128                                 {product}
    public Boolean ConvertSleepToYield; // = true                                {pd product}
    public Boolean ConvertYieldToSleep; // = false                               {product}
    public Boolean CrashOnOutOfMemoryError; // = false                               {product}
    public Boolean CreateMinidumpOnCrash; // = false                               {product}
    public Boolean CriticalJNINatives; // = true                                {product}
    public Boolean DTraceAllocProbes; // = false                               {product}
    public Boolean DTraceMethodProbes; // = false                               {product}
    public Boolean DTraceMonitorProbes; // = false                               {product}
    public Boolean Debugging; // = false                               {product}
    public Integer DefaultMaxRAMFraction; // = 4                                   {product}
    public Integer DefaultThreadPriority; // = -1                                  {product}
    public Integer DeferPollingPageLoopCount; // = -1                                  {product}
    public Integer DeferThrSuspendLoopCount; // = 4000                                {product}
    public Boolean DeoptimizeRandom; // = false                               {product}
    public Boolean DisableAttachMechanism; // = false                               {product}
    public Boolean DisableExplicitGC; // = false                               {product}
    public Boolean DisplayVMOutputToStderr; // = false                               {product}
    public Boolean DisplayVMOutputToStdout; // = false                               {product}
    public Boolean DoEscapeAnalysis; // = true                                {C2 product}
    public Boolean DontCompileHugeMethods; // = true                                {product}
    public Boolean DontYieldALot; // = false                               {pd product}
    public File DumpLoadedClassList; // =                                     {product}
    public Boolean DumpReplayDataOnError; // = true                                {product}
    public Boolean DumpSharedSpaces; // = false                               {product}
    public Boolean EagerXrunInit; // = false                               {product}
    public Integer EliminateAllocationArraySizeLimit; // = 64                                  {C2 product}
    public Boolean EliminateAllocations; // = true                                {C2 product}
    public Boolean EliminateAutoBox; // = true                                {C2 product}
    public Boolean EliminateLocks; // = true                                {C2 product}
    public Boolean EliminateNestedLocks; // = true                                {C2 product}
    public Integer EmitSync; // = 0                                   {product}
    public Boolean EnableContended; // = true                                {product}
    public Integer ErgoHeapSizeLimit; // = 0                                   {product}
    public File ErrorFile; // =                                     {product}
    public String ErrorReportServer; // =                                     {product}
    public Double EscapeAnalysisTimeout; // = 20.000000                           {C2 product}
    public Boolean EstimateArgEscape; // = true                                {product}
    public Boolean ExitOnOutOfMemoryError; // = false                               {product}
    public Boolean ExplicitGCInvokesConcurrent; // = false                               {product}
    public Boolean ExplicitGCInvokesConcurrentAndUnloadsClasses; // = false                               {product}
    public Boolean ExtendedDTraceProbes; // = false                               {product}
    public String ExtraSharedClassListFile; // =                                     {product}
    public Boolean FLSAlwaysCoalesceLarge; // = false                               {product}
    public Integer FLSCoalescePolicy; // = 2                                   {product}
    public Double FLSLargestBlockCoalesceProximity; // = 0.990000                            {product}
    public Boolean FailOverToOldVerifier; // = true                                {product}
    public Boolean FastTLABRefill; // = true                                {product}
    public Integer FenceInstruction; // = 0                                   {ARCH product}
    public Integer FieldsAllocationStyle; // = 1                                   {product}
    public Boolean FilterSpuriousWakeups; // = true                                {product}
    public Boolean FlightRecorder; // = false                               {product}
    public String FlightRecorderOptions; // =                                     {product}
    public Boolean ForceNUMA; // = false                               {product}
    public Boolean ForceTimeHighResolution; // = false                               {product}
    public Integer FreqInlineSize; // = 325                                 {pd product}
    public Double G1ConcMarkStepDurationMillis; // = 10.000000                           {product}
    public Integer G1ConcRSHotCardLimit; // = 4                                   {product}
    public Integer G1ConcRSLogCacheSize; // = 10                                  {product}
    public Integer G1ConcRefinementGreenZone; // = 0                                   {product}
    public Integer G1ConcRefinementRedZone; // = 0                                   {product}
    public Integer G1ConcRefinementServiceIntervalMillis; // = 300                                 {product}
    public Integer G1ConcRefinementThreads; // = 0                                   {product}
    public Integer G1ConcRefinementThresholdStep; // = 0                                   {product}
    public Integer G1ConcRefinementYellowZone; // = 0                                   {product}
    public Integer G1ConfidencePercent; // = 50                                  {product}
    public Integer G1HeapRegionSize; // = 0                                   {product}
    public Integer G1HeapWastePercent; // = 5                                   {product}
    public Integer G1MixedGCCountTarget; // = 8                                   {product}
    public Integer G1RSetRegionEntries; // = 0                                   {product}
    public Integer G1RSetScanBlockSize; // = 64                                  {product}
    public Integer G1RSetSparseRegionEntries; // = 0                                   {product}
    public Integer G1RSetUpdatingPauseTimePercent; // = 10                                  {product}
    public Integer G1RefProcDrainInterval; // = 10                                  {product}
    public Integer G1ReservePercent; // = 10                                  {product}
    public Integer G1SATBBufferEnqueueingThresholdPercent; // = 60                                  {product}
    public Integer G1SATBBufferSize; // = 1024                                {product}
    public Integer G1UpdateBufferSize; // = 256                                 {product}
    public Boolean G1UseAdaptiveConcRefinement; // = true                                {product}
    public Integer GCDrainStackTargetSize; // = 64                                  {product}
    public Integer GCHeapFreeLimit; // = 2                                   {product}
    public Integer GCLockerEdenExpansionPercent; // = 5                                   {product}
    public Boolean GCLockerInvokesConcurrent; // = false                               {product}
    public Integer GCLogFileSize; // = 8192                                {product}
    public Integer GCPauseIntervalMillis; // = 0                                   {product}
    public Integer GCTaskTimeStampEntries; // = 200                                 {product}
    public Integer GCTimeLimit; // = 98                                  {product}
    public Integer GCTimeRatio; // = 99                                  {product}
    public Integer HeapBaseMinAddress; // = 2147483648                          {pd product}
    public Boolean HeapDumpAfterFullGC; // = false                               {manageable}
    public Boolean HeapDumpBeforeFullGC; // = false                               {manageable}
    public Boolean HeapDumpOnOutOfMemoryError; // = false                               {manageable}
    public File HeapDumpPath; // =                                     {manageable}
    public Integer HeapFirstMaximumCompactionCount; // = 3                                   {product}
    public Integer HeapMaximumCompactionInterval; // = 20                                  {product}
    public Integer HeapSizePerGCThread; // = 87241520                            {product}
    public Boolean IgnoreEmptyClassPaths; // = false                               {product}
    public Boolean IgnoreUnrecognizedVMOptions; // = false                               {product}
    public Integer IncreaseFirstTierCompileThresholdAt; // = 50                                  {product}
    public Boolean IncrementalInline; // = true                                {C2 product}
    public Integer InitialBootClassLoaderMetaspaceSize; // = 4194304                             {product}
    public Integer InitialCodeCacheSize; // = 2555904                             {pd product}
    public Integer InitialHeapSize; // = 534773760                           {product}
    public Integer InitialRAMFraction; // = 64                                  {product}
    public Double InitialRAMPercentage; // = 1.562500                            {product}
    public Integer InitialSurvivorRatio; // = 8                                   {product}
    public Integer InitialTenuringThreshold; // = 7                                   {product}
    public Integer InitiatingHeapOccupancyPercent; // = 45                                  {product}
    public Boolean Inline; // = true                                {product}
    public File InlineDataFile; // =                                     {product}
    public Integer InlineSmallCode; // = 2000                                {pd product}
    public Boolean InlineSynchronizedMethods; // = true                                {C1 product}
    public Boolean InsertMemBarAfterArraycopy; // = true                                {C2 product}
    public Integer InteriorEntryAlignment; // = 16                                  {C2 pd product}
    public Integer InterpreterProfilePercentage; // = 33                                  {product}
    public Boolean JNIDetachReleasesMonitors; // = true                                {product}
    public Boolean JavaMonitorsInStackTrace; // = true                                {product}
    public Integer JavaPriority10_To_OSPriority; // = -1                                  {product}
    public Integer JavaPriority1_To_OSPriority; // = -1                                  {product}
    public Integer JavaPriority2_To_OSPriority; // = -1                                  {product}
    public Integer JavaPriority3_To_OSPriority; // = -1                                  {product}
    public Integer JavaPriority4_To_OSPriority; // = -1                                  {product}
    public Integer JavaPriority5_To_OSPriority; // = -1                                  {product}
    public Integer JavaPriority6_To_OSPriority; // = -1                                  {product}
    public Integer JavaPriority7_To_OSPriority; // = -1                                  {product}
    public Integer JavaPriority8_To_OSPriority; // = -1                                  {product}
    public Integer JavaPriority9_To_OSPriority; // = -1                                  {product}
    public Boolean LIRFillDelaySlots; // = false                               {C1 pd product}
    public Integer LargePageHeapSizeThreshold; // = 134217728                           {product}
    public Integer LargePageSizeInBytes; // = 0                                   {product}
    public Boolean LazyBootClassLoader; // = true                                {product}
    public Integer LiveNodeCountInliningCutoff; // = 40000                               {C2 product}
    public Boolean LogJFR; // = false                               {product}
    public Integer LoopMaxUnroll; // = 16                                  {C2 product}
    public Integer LoopOptsCount; // = 43                                  {C2 product}
    public Integer LoopUnrollLimit; // = 60                                  {C2 pd product}
    public Integer LoopUnrollMin; // = 4                                   {C2 product}
    public Boolean LoopUnswitching; // = true                                {C2 product}
    public Boolean ManagementServer; // = false                               {product}
    public Integer MarkStackSize; // = 4194304                             {product}
    public Integer MarkStackSizeMax; // = 536870912                           {product}
    public Integer MarkSweepAlwaysCompactCount; // = 4                                   {product}
    public Integer MarkSweepDeadRatio; // = 1                                   {product}
    public Integer MaxBCEAEstimateLevel; // = 5                                   {product}
    public Integer MaxBCEAEstimateSize; // = 150                                 {product}
    public Integer MaxDirectMemorySize; // = 0                                   {product}
    public Boolean MaxFDLimit; // = true                                {product}
    public Integer MaxGCMinorPauseMillis; // = 4294967295                          {product}
    public Integer MaxGCPauseMillis; // = 4294967295                          {product}
    public Integer MaxHeapFreeRatio; // = 100                                 {manageable}
    public Integer MaxHeapSize; // = 4261412864                          {product}
    public Integer MaxInlineLevel; // = 9                                   {product}
    public Integer MaxInlineSize; // = 35                                  {product}
    public Integer MaxJNILocalCapacity; // = 65536                               {product}
    public Integer MaxJavaStackTraceDepth; // = 1024                                {product}
    public Integer MaxJumpTableSize; // = 65000                               {C2 product}
    public Integer MaxJumpTableSparseness; // = 5                                   {C2 product}
    public Integer MaxLabelRootDepth; // = 1100                                {C2 product}
    public Integer MaxLoopPad; // = 11                                  {C2 product}
    public Integer MaxMetaspaceExpansion; // = 5451776                             {product}
    public Integer MaxMetaspaceFreeRatio; // = 70                                  {product}
    public Integer MaxMetaspaceSize; // = 4294901760                          {product}
    public Integer MaxNewSize; // = 2852126720                          {product}
    public Integer MaxNodeLimit; // = 75000                               {C2 product}
    public Long MaxRAM; // = 0                                   {pd product}
    public Integer MaxRAMFraction; // = 4                                   {product}
    public Double MaxRAMPercentage; // = 25.000000                           {product}
    public Integer MaxRecursiveInlineLevel; // = 1                                   {product}
    public Integer MaxTenuringThreshold; // = 15                                  {product}
    public Integer MaxTrivialSize; // = 6                                   {product}
    public Integer MaxVectorSize; // = 32                                  {C2 product}
    public Integer MetaspaceSize; // = 21807104                            {pd product}
    public Boolean MethodFlushing; // = true                                {product}
    public Integer MinHeapDeltaBytes; // = 524288                              {product}
    public Integer MinHeapFreeRatio; // = 0                                   {manageable}
    public Integer MinInliningThreshold; // = 250                                 {product}
    public Integer MinJumpTableSize; // = 10                                  {C2 pd product}
    public Integer MinMetaspaceExpansion; // = 339968                              {product}
    public Integer MinMetaspaceFreeRatio; // = 40                                  {product}
    public Integer MinRAMFraction; // = 2                                   {product}
    public Double MinRAMPercentage; // = 50.000000                           {product}
    public Integer MinSurvivorRatio; // = 3                                   {product}
    public Integer MinTLABSize; // = 2048                                {product}
    public Integer MonitorBound; // = 0                                   {product}
    public Boolean MonitorInUseLists; // = false                               {product}
    public Integer MultiArrayExpandLimit; // = 6                                   {C2 product}
    public Boolean MustCallLoadClassInternal; // = false                               {product}
    public Integer NUMAChunkResizeWeight; // = 20                                  {product}
    public Integer NUMAInterleaveGranularity; // = 2097152                             {product}
    public Integer NUMAPageScanRate; // = 256                                 {product}
    public Integer NUMASpaceResizeRate; // = 1073741824                          {product}
    public Boolean NUMAStats; // = false                               {product}
    public String NativeMemoryTracking; // = off                                 {product}
    public Boolean NeedsDeoptSuspend; // = false                               {pd product}
    public Boolean NeverActAsServerClassMachine; // = false                               {pd product}
    public Boolean NeverTenure; // = false                               {product}
    public Integer NewRatio; // = 2                                   {product}
    public Integer NewSize; // = 178257920                           {product}
    public Integer NewSizeThreadIncrease; // = 5320                                {pd product}
    public Integer NmethodSweepActivity; // = 10                                  {product}
    public Integer NmethodSweepCheckInterval; // = 5                                   {product}
    public Integer NmethodSweepFraction; // = 16                                  {product}
    public Integer NodeLimitFudgeFactor; // = 2000                                {C2 product}
    public Integer NumberOfGCLogFiles; // = 0                                   {product}
    public Integer NumberOfLoopInstrToAlign; // = 4                                   {C2 product}
    public Integer ObjectAlignmentInBytes; // = 8                                   {lp64_product}
    public Integer OldPLABSize; // = 1024                                {product}
    public Integer OldPLABWeight; // = 50                                  {product}
    public Integer OldSize; // = 356515840                           {product}
    public Boolean OmitStackTraceInFastThrow; // = true                                {product}
    public String OnError; // =                                     {product}
    public String OnOutOfMemoryError; // =                                     {product}
    public Integer OnStackReplacePercentage; // = 140                                 {pd product}
    public Boolean OptimizeFill; // = true                                {C2 product}
    public Boolean OptimizePtrCompare; // = true                                {C2 product}
    public Boolean OptimizeStringConcat; // = true                                {C2 product}
    public Boolean OptoBundling; // = false                               {C2 pd product}
    public Integer OptoLoopAlignment; // = 16                                  {pd product}
    public Boolean OptoScheduling; // = false                               {C2 pd product}
    public Boolean OverrideVMProperties; // = false                               {product}
    public Integer PLABWeight; // = 75                                  {product}
    public Boolean PSChunkLargeArrays; // = true                                {product}
    public Integer ParGCArrayScanChunk; // = 50                                  {product}
    public Integer ParGCDesiredObjsFromOverflowList; // = 20                                  {product}
    public Boolean ParGCTrimOverflow; // = true                                {product}
    public Boolean ParGCUseLocalOverflow; // = false                               {product}
    public Integer ParallelGCBufferWastePct; // = 10                                  {product}
    public Integer ParallelGCThreads; // = 8                                   {product}
    public Boolean ParallelGCVerbose; // = false                               {product}
    public Integer ParallelOldDeadWoodLimiterMean; // = 50                                  {product}
    public Integer ParallelOldDeadWoodLimiterStdDev; // = 80                                  {product}
    public Boolean ParallelRefProcBalancingEnabled; // = true                                {product}
    public Boolean ParallelRefProcEnabled; // = false                               {product}
    public Boolean PartialPeelAtUnsignedTests; // = true                                {C2 product}
    public Boolean PartialPeelLoop; // = true                                {C2 product}
    public Integer PartialPeelNewPhiDelta; // = 0                                   {C2 product}
    public Integer PausePadding; // = 1                                   {product}
    public Integer PerBytecodeRecompilationCutoff; // = 200                                 {product}
    public Integer PerBytecodeTrapLimit; // = 4                                   {product}
    public Integer PerMethodRecompilationCutoff; // = 400                                 {product}
    public Integer PerMethodTrapLimit; // = 100                                 {product}
    public Boolean PerfAllowAtExitRegistration; // = false                               {product}
    public Boolean PerfBypassFileSystemCheck; // = false                               {product}
    public Integer PerfDataMemorySize; // = 32768                               {product}
    public Integer PerfDataSamplingInterval; // = 50                                  {product}
    public File PerfDataSaveFile; // =                                     {product}
    public Boolean PerfDataSaveToFile; // = false                               {product}
    public Boolean PerfDisableSharedMem; // = false                               {product}
    public Integer PerfMaxStringConstLength; // = 1024                                {product}
    public Integer PreInflateSpin; // = 10                                  {pd product}
    public Boolean PreferInterpreterNativeStubs; // = false                               {pd product}
    public Integer PrefetchCopyIntervalInBytes; // = 576                                 {product}
    public Integer PrefetchFieldsAhead; // = 1                                   {product}
    public Integer PrefetchScanIntervalInBytes; // = 576                                 {product}
    public Boolean PreserveAllAnnotations; // = false                               {product}
    public Boolean PreserveFramePointer; // = false                               {pd product}
    public Integer PretenureSizeThreshold; // = 0                                   {product}
    public Boolean PrintAdaptiveSizePolicy; // = false                               {product}
    public Boolean PrintCMSInitiationStatistics; // = false                               {product}
    public Integer PrintCMSStatistics; // = 0                                   {product}
    public Boolean PrintClassHistogram; // = false                               {manageable}
    public Boolean PrintClassHistogramAfterFullGC; // = false                               {manageable}
    public Boolean PrintClassHistogramBeforeFullGC; // = false                               {manageable}
    public Boolean PrintCodeCache; // = false                               {product}
    public Boolean PrintCodeCacheOnCompilation; // = false                               {product}
    public Boolean PrintCommandLineFlags; // = false                               {product}
    public Boolean PrintCompilation; // = false                               {product}
    public Boolean PrintConcurrentLocks; // = false                               {manageable}
    public Integer PrintFLSCensus; // = 0                                   {product}
    public Integer PrintFLSStatistics; // = 0                                   {product}
    public Boolean PrintFlagsFinal; // = true                                {product}
    public Boolean PrintFlagsInitial; // = false                               {product}
    public Boolean PrintGC; // = false                               {manageable}
    public Boolean PrintGCApplicationConcurrentTime; // = false                               {product}
    public Boolean PrintGCApplicationStoppedTime; // = false                               {product}
    public Boolean PrintGCCause; // = true                                {product}
    public Boolean PrintGCDateStamps; // = false                               {manageable}
    public Boolean PrintGCDetails; // = false                               {manageable}
    public Boolean PrintGCID; // = false                               {manageable}
    public Boolean PrintGCTaskTimeStamps; // = false                               {product}
    public Boolean PrintGCTimeStamps; // = false                               {manageable}
    public Boolean PrintHeapAtGC; // = false                               {product rw}
    public Boolean PrintHeapAtGCExtended; // = false                               {product rw}
    public Boolean PrintHeapAtSIGBREAK; // = true                                {product}
    public Boolean PrintJNIGCStalls; // = false                               {product}
    public Boolean PrintJNIResolving; // = false                               {product}
    public Boolean PrintOldPLAB; // = false                               {product}
    public Boolean PrintOopAddress; // = false                               {product}
    public Boolean PrintPLAB; // = false                               {product}
    public Boolean PrintParallelOldGCPhaseTimes; // = false                               {product}
    public Boolean PrintPromotionFailure; // = false                               {product}
    public Boolean PrintReferenceGC; // = false                               {product}
    public Boolean PrintSafepointStatistics; // = false                               {product}
    public Integer PrintSafepointStatisticsCount; // = 300                                 {product}
    public Integer PrintSafepointStatisticsTimeout; // = -1                                  {product}
    public Boolean PrintSharedArchiveAndExit; // = false                               {product}
    public Boolean PrintSharedDictionary; // = false                               {product}
    public Boolean PrintSharedSpaces; // = false                               {product}
    public Boolean PrintStringDeduplicationStatistics; // = false                               {product}
    public Boolean PrintStringTableStatistics; // = false                               {product}
    public Boolean PrintTLAB; // = false                               {product}
    public Boolean PrintTenuringDistribution; // = false                               {product}
    public Boolean PrintTieredEvents; // = false                               {product}
    public Boolean PrintVMOptions; // = false                               {product}
    public Boolean PrintVMQWaitTime; // = false                               {product}
    public Boolean PrintWarnings; // = true                                {product}
    public Integer ProcessDistributionStride; // = 4                                   {product}
    public Boolean ProfileInterpreter; // = true                                {pd product}
    public Boolean ProfileIntervals; // = false                               {product}
    public Integer ProfileIntervalsTicks; // = 100                                 {product}
    public Integer ProfileMaturityPercentage; // = 20                                  {product}
    public Boolean ProfileVM; // = false                               {product}
    public Boolean ProfilerPrintByteCodeStatistics; // = false                               {product}
    public Boolean ProfilerRecordPC; // = false                               {product}
    public Integer PromotedPadding; // = 3                                   {product}
    public Integer QueuedAllocationWarningCount; // = 0                                   {product}
    public Integer RTMRetryCount; // = 5                                   {ARCH product}
    public Boolean RangeCheckElimination; // = true                                {product}
    public Integer ReadPrefetchInstr; // = 0                                   {ARCH product}
    public Boolean ReassociateInvariants; // = true                                {C2 product}
    public Boolean ReduceBulkZeroing; // = true                                {C2 product}
    public Boolean ReduceFieldZeroing; // = true                                {C2 product}
    public Boolean ReduceInitialCardMarks; // = true                                {C2 product}
    public Boolean ReduceSignalUsage; // = false                               {product}
    public Integer RefDiscoveryPolicy; // = 0                                   {product}
    public Boolean ReflectionWrapResolutionErrors; // = true                                {product}
    public Boolean RegisterFinalizersAtInit; // = true                                {product}
    public Boolean RelaxAccessControlCheck; // = false                               {product}
    public String ReplayDataFile; // =                                     {product}
    public Boolean RequireSharedSpaces; // = false                               {product}
    public Integer ReservedCodeCacheSize; // = 251658240                           {pd product}
    public Boolean ResizeOldPLAB; // = true                                {product}
    public Boolean ResizePLAB; // = true                                {product}
    public Boolean ResizeTLAB; // = true                                {pd product}
    public Boolean RestoreMXCSROnJNICalls; // = false                               {product}
    public Boolean RestrictContended; // = true                                {product}
    public Boolean RestrictReservedStack; // = true                                {product}
    public Boolean RewriteBytecodes; // = true                                {pd product}
    public Boolean RewriteFrequentPairs; // = true                                {pd product}
    public Integer SafepointPollOffset; // = 256                                 {C1 pd product}
    public Integer SafepointSpinBeforeYield; // = 2000                                {product}
    public Boolean SafepointTimeout; // = false                               {product}
    public Integer SafepointTimeoutDelay; // = 10000                               {product}
    public Boolean ScavengeBeforeFullGC; // = true                                {product}
    public Integer SelfDestructTimer; // = 0                                   {product}
    public Integer SharedBaseAddress; // = 0                                   {product}
    public File SharedClassListFile; // =                                     {product}
    public Integer SharedMiscCodeSize; // = 122880                              {product}
    public Integer SharedMiscDataSize; // = 4194304                             {product}
    public Integer SharedReadOnlySize; // = 16777216                            {product}
    public Integer SharedReadWriteSize; // = 16777216                            {product}
    public Boolean ShowMessageBoxOnError; // = false                               {product}
    public Integer SoftRefLRUPolicyMSPerMB; // = 1000                                {product}
    public Boolean SpecialEncodeISOArray; // = true                                {C2 product}
    public Boolean SplitIfBlocks; // = true                                {C2 product}
    public Integer StackRedPages; // = 1                                   {pd product}
    public Integer StackReservedPages; // = 0                                   {pd product}
    public Integer StackShadowPages; // = 6                                   {pd product}
    public Boolean StackTraceInThrowable; // = true                                {product}
    public Integer StackYellowPages; // = 3                                   {pd product}
    public Boolean StartAttachListener; // = false                               {product}
    public String StartFlightRecording; // =                                     {product}
    public Integer StarvationMonitorInterval; // = 200                                 {product}
    public Boolean StressLdcRewrite; // = false                               {product}
    public Integer StringDeduplicationAgeThreshold; // = 3                                   {product}
    public Integer StringTableSize; // = 60013                               {product}
    public Boolean SuppressFatalErrorMessage; // = false                               {product}
    public Integer SurvivorPadding; // = 3                                   {product}
    public Integer SurvivorRatio; // = 8                                   {product}
    public Integer SuspendRetryCount; // = 50                                  {product}
    public Integer SuspendRetryDelay; // = 5                                   {product}
    public Integer SyncFlags; // = 0                                   {product}
    public String SyncKnobs; // =                                     {product}
    public Integer SyncVerbose; // = 0                                   {product}
    public Integer TLABAllocationWeight; // = 35                                  {product}
    public Integer TLABRefillWasteFraction; // = 64                                  {product}
    public Integer TLABSize; // = 0                                   {product}
    public Boolean TLABStats; // = true                                {product}
    public Integer TLABWasteIncrement; // = 4                                   {product}
    public Integer TLABWasteTargetPercent; // = 1                                   {product}
    public Integer TargetPLABWastePct; // = 10                                  {product}
    public Integer TargetSurvivorRatio; // = 50                                  {product}
    public Integer TenuredGenerationSizeIncrement; // = 20                                  {product}
    public Integer TenuredGenerationSizeSupplement; // = 80                                  {product}
    public Integer TenuredGenerationSizeSupplementDecay; // = 2                                   {product}
    public Integer ThreadPriorityPolicy; // = 0                                   {product}
    public Boolean ThreadPriorityVerbose; // = false                               {product}
    public Integer ThreadSafetyMargin; // = 52428800                            {product}
    public Integer ThreadStackSize; // = 0                                   {pd product}
    public Integer ThresholdTolerance; // = 10                                  {product}
    public Integer Tier0BackedgeNotifyFreqLog; // = 10                                  {product}
    public Integer Tier0InvokeNotifyFreqLog; // = 7                                   {product}
    public Integer Tier0ProfilingStartPercentage; // = 200                                 {product}
    public Integer Tier23InlineeNotifyFreqLog; // = 20                                  {product}
    public Integer Tier2BackEdgeThreshold; // = 0                                   {product}
    public Integer Tier2BackedgeNotifyFreqLog; // = 14                                  {product}
    public Integer Tier2CompileThreshold; // = 0                                   {product}
    public Integer Tier2InvokeNotifyFreqLog; // = 11                                  {product}
    public Integer Tier3BackEdgeThreshold; // = 60000                               {product}
    public Integer Tier3BackedgeNotifyFreqLog; // = 13                                  {product}
    public Integer Tier3CompileThreshold; // = 2000                                {product}
    public Integer Tier3DelayOff; // = 2                                   {product}
    public Integer Tier3DelayOn; // = 5                                   {product}
    public Integer Tier3InvocationThreshold; // = 200                                 {product}
    public Integer Tier3InvokeNotifyFreqLog; // = 10                                  {product}
    public Integer Tier3LoadFeedback; // = 5                                   {product}
    public Integer Tier3MinInvocationThreshold; // = 100                                 {product}
    public Integer Tier4BackEdgeThreshold; // = 40000                               {product}
    public Integer Tier4CompileThreshold; // = 15000                               {product}
    public Integer Tier4InvocationThreshold; // = 5000                                {product}
    public Integer Tier4LoadFeedback; // = 3                                   {product}
    public Integer Tier4MinInvocationThreshold; // = 600                                 {product}
    public Boolean TieredCompilation; // = true                                {pd product}
    public Integer TieredCompileTaskTimeout; // = 50                                  {product}
    public Integer TieredRateUpdateMaxTime; // = 25                                  {product}
    public Integer TieredRateUpdateMinTime; // = 1                                   {product}
    public Integer TieredStopAtLevel; // = 4                                   {product}
    public Boolean TimeLinearScan; // = false                               {C1 product}
    public Boolean TraceBiasedLocking; // = false                               {product}
    public Boolean TraceBiasedLockingDateStamp; // = false                               {product}
    public Boolean TraceClassLoading; // = false                               {product rw}
    public Boolean TraceClassLoadingPreorder; // = false                               {product}
    public Boolean TraceClassPaths; // = false                               {product}
    public Boolean TraceClassResolution; // = false                               {product}
    public Boolean TraceClassUnloading; // = false                               {product rw}
    public Boolean TraceDynamicGCThreads; // = false                               {product}
    public Boolean TraceGen0Time; // = false                               {product}
    public Boolean TraceGen1Time; // = false                               {product}
    public String TraceJVMTI; // =                                     {product}
    public Boolean TraceLoaderConstraints; // = false                               {product rw}
    public Boolean TraceMetadataHumongousAllocation; // = false                               {product}
    public Boolean TraceMonitorInflation; // = false                               {product}
    public Boolean TraceParallelOldGCTasks; // = false                               {product}
    public Integer TraceRedefineClasses; // = 0                                   {product}
    public Boolean TraceSafepointCleanupTime; // = false                               {product}
    public Boolean TraceSuspendWaitFailures; // = false                               {product}
    public Integer TrackedInitializationLimit; // = 50                                  {C2 product}
    public Boolean TransmitErrorReport; // = false                               {product}
    public Boolean TrapBasedNullChecks; // = false                               {pd product}
    public Boolean TrapBasedRangeChecks; // = false                               {C2 pd product}
    public Integer TypeProfileArgsLimit; // = 2                                   {product}
    public Integer TypeProfileLevel; // = 111                                 {pd product}
    public Integer TypeProfileMajorReceiverPercent; // = 90                                  {C2 product}
    public Integer TypeProfileParmsLimit; // = 2                                   {product}
    public Integer TypeProfileWidth; // = 2                                   {product}
    public Integer UnguardOnExecutionViolation; // = 0                                   {product}
    public Boolean UnlinkSymbolsALot; // = false                               {product}
    public Boolean UnlockCommercialFeatures; // = false                               {product}
    public Boolean Use486InstrsOnly; // = false                               {ARCH product}
    public Boolean UseAES; // = true                                {product}
    public Boolean UseAESCTRIntrinsics; // = true                                {product}
    public Boolean UseAESIntrinsics; // = true                                {product}
    public Integer UseAVX; // = 2                                   {ARCH product}
    public Boolean UseAdaptiveGCBoundary; // = false                               {product}
    public Boolean UseAdaptiveGenerationSizePolicyAtMajorCollection; // = true                                {product}
    public Boolean UseAdaptiveGenerationSizePolicyAtMinorCollection; // = true                                {product}
    public Boolean UseAdaptiveNUMAChunkSizing; // = true                                {product}
    public Boolean UseAdaptiveSizeDecayMajorGCCost; // = true                                {product}
    public Boolean UseAdaptiveSizePolicy; // = true                                {product}
    public Boolean UseAdaptiveSizePolicyFootprintGoal; // = true                                {product}
    public Boolean UseAdaptiveSizePolicyWithSystemGC; // = false                               {product}
    public Boolean UseAddressNop; // = true                                {ARCH product}
    public Boolean UseAltSigs; // = false                               {product}
    public Boolean UseAutoGCSelectPolicy; // = false                               {product}
    public Boolean UseBMI1Instructions; // = true                                {ARCH product}
    public Boolean UseBMI2Instructions; // = true                                {ARCH product}
    public Boolean UseBiasedLocking; // = true                                {product}
    public Boolean UseBimorphicInlining; // = true                                {C2 product}
    public Boolean UseBoundThreads; // = true                                {product}
    public Boolean UseCLMUL; // = true                                {ARCH product}
    public Boolean UseCMSBestFit; // = true                                {product}
    public Boolean UseCMSCollectionPassing; // = true                                {product}
    public Boolean UseCMSCompactAtFullCollection; // = true                                {product}
    public Boolean UseCMSInitiatingOccupancyOnly; // = false                               {product}
    public Boolean UseCRC32Intrinsics; // = true                                {product}
    public Boolean UseCodeCacheFlushing; // = true                                {product}
    public Boolean UseCompiler; // = true                                {product}
    public Boolean UseCompilerSafepoints; // = true                                {product}
    public Boolean UseCompressedClassPointers; // = true                                {lp64_product}
    public Boolean UseCompressedOops; // = true                                {lp64_product}
    public Boolean UseConcMarkSweepGC; // = false                               {product}
    public Boolean UseCondCardMark; // = false                               {C2 product}
    public Boolean UseCountLeadingZerosInstruction; // = true                                {ARCH product}
    public Boolean UseCountTrailingZerosInstruction; // = true                                {ARCH product}
    public Boolean UseCountedLoopSafepoints; // = false                               {C2 product}
    public Boolean UseCounterDecay; // = true                                {product}
    public Boolean UseDivMod; // = true                                {C2 product}
    public Boolean UseDynamicNumberOfGCThreads; // = false                               {product}
    public Boolean UseFPUForSpilling; // = true                                {C2 product}
    public Boolean UseFastAccessorMethods; // = false                               {product}
    public Boolean UseFastEmptyMethods; // = false                               {product}
    public Boolean UseFastJNIAccessors; // = true                                {product}
    public Boolean UseFastStosb; // = true                                {ARCH product}
    public Boolean UseG1GC; // = false                               {product}
    public Boolean UseGCLogFileRotation; // = false                               {product}
    public Boolean UseGCOverheadLimit; // = true                                {product}
    public Boolean UseGCTaskAffinity; // = false                               {product}
    public Boolean UseGHASHIntrinsics; // = true                                {product}
    public Boolean UseHeavyMonitors; // = false                               {product}
    public Boolean UseInlineCaches; // = true                                {product}
    public Boolean UseInterpreter; // = true                                {product}
    public Boolean UseJumpTables; // = true                                {C2 product}
    public Boolean UseLWPSynchronization; // = true                                {product}
    public Boolean UseLargePages; // = false                               {pd product}
    public Boolean UseLargePagesInMetaspace; // = false                               {product}
    public Boolean UseLargePagesIndividualAllocation; // = false                               {pd product}
    public Boolean UseLoopCounter; // = true                                {product}
    public Boolean UseLoopInvariantCodeMotion; // = true                                {C1 product}
    public Boolean UseLoopPredicate; // = true                                {C2 product}
    public Boolean UseMathExactIntrinsics; // = true                                {C2 product}
    public Boolean UseMaximumCompactionOnSystemGC; // = true                                {product}
    public Boolean UseMembar; // = false                               {pd product}
    public Boolean UseMontgomeryMultiplyIntrinsic; // = true                                {C2 product}
    public Boolean UseMontgomerySquareIntrinsic; // = true                                {C2 product}
    public Boolean UseMulAddIntrinsic; // = true                                {C2 product}
    public Boolean UseMultiplyToLenIntrinsic; // = true                                {C2 product}
    public Boolean UseNUMA; // = false                               {product}
    public Boolean UseNUMAInterleaving; // = false                               {product}
    public Boolean UseNewLongLShift; // = false                               {ARCH product}
    public Boolean UseOSErrorReporting; // = false                               {pd product}
    public Boolean UseOnStackReplacement; // = true                                {pd product}
    public Boolean UseOnlyInlinedBimorphic; // = true                                {C2 product}
    public Boolean UseOpenJSSE; // = false                               {product}
    public Boolean UseOptoBiasInlining; // = true                                {C2 product}
    public Boolean UsePSAdaptiveSurvivorSizePolicy; // = true                                {product}
    public Boolean UseParNewGC; // = false                               {product}
    public Boolean UseParallelGC; // = true                                {product}
    public Boolean UseParallelOldGC; // = true                                {product}
    public Boolean UsePerfData; // = true                                {product}
    public Boolean UsePopCountInstruction; // = true                                {product}
    public Boolean UseRDPCForConstantTableBase; // = false                               {C2 product}
    public Boolean UseRTMDeopt; // = false                               {ARCH product}
    public Boolean UseRTMLocking; // = false                               {ARCH product}
    public Boolean UseSHA; // = false                               {product}
    public Boolean UseSHA1Intrinsics; // = false                               {product}
    public Boolean UseSHA256Intrinsics; // = false                               {product}
    public Boolean UseSHA512Intrinsics; // = false                               {product}
    public Integer UseSSE; // = 4                                   {product}
    public Boolean UseSSE42Intrinsics; // = true                                {product}
    public Boolean UseSerialGC; // = false                               {product}
    public Boolean UseSharedSpaces; // = false                               {product}
    public Boolean UseSignalChaining; // = true                                {product}
    public Boolean UseSquareToLenIntrinsic; // = true                                {C2 product}
    public Boolean UseStoreImmI16; // = false                               {ARCH product}
    public Boolean UseStringDeduplication; // = false                               {product}
    public Boolean UseSuperWord; // = true                                {C2 product}
    public Boolean UseTLAB; // = true                                {pd product}
    public Boolean UseThreadPriorities; // = true                                {pd product}
    public Boolean UseTypeProfile; // = true                                {product}
    public Boolean UseTypeSpeculation; // = true                                {C2 product}
    public Boolean UseUTCFileTimestamp; // = true                                {product}
    public Boolean UseUnalignedLoadStores; // = true                                {ARCH product}
    public Boolean UseVMInterruptibleIO; // = false                               {product}
    public Boolean UseXMMForArrayCopy; // = true                                {product}
    public Boolean UseXmmI2D; // = false                               {ARCH product}
    public Boolean UseXmmI2F; // = false                               {ARCH product}
    public Boolean UseXmmLoadAndClearUpper; // = true                                {ARCH product}
    public Boolean UseXmmRegToRegMoveAll; // = true                                {ARCH product}
    public Boolean VMThreadHintNoPreempt; // = false                               {product}
    public Integer VMThreadPriority; // = -1                                  {product}
    public Integer VMThreadStackSize; // = 0                                   {pd product}
    public Integer ValueMapInitialSize; // = 11                                  {C1 product}
    public Integer ValueMapMaxLoopSize; // = 8                                   {C1 product}
    public Integer ValueSearchLimit; // = 1000                                {C2 product}
    public Boolean VerifyMergedCPBytecodes; // = true                                {product}
    public Boolean VerifySharedSpaces; // = false                               {product}
    public Integer WorkAroundNPTLTimedWaitHang; // = 1                                   {product}
    public Integer YoungGenerationSizeIncrement; // = 20                                  {product}
    public Integer YoungGenerationSizeSupplement; // = 80                                  {product}
    public Integer YoungGenerationSizeSupplementDecay; // = 8                                   {product}
    public Integer YoungPLABSize; // = 4096                                {product}
    public Boolean ZeroTLAB; // = false                               {product}
    public Integer hashCode; // = 5                                   {product}


    // manual
    public Boolean UseShenandoahGC;
    ;


}
